version: "3.8"
services:
    nodeserver:
        build:
            context: ./tftprojeto
        ports:
            - "6031:6031"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"

networks:
    default:
        name: patroni_tftproject
        external: true 